# This is a basic workflow to help you get started with Actions

name: ImmortalWrt

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Clone repository
        run: git clone -b master --single-branch --filter=blob:none https://github.com/immortalwrt/immortalwrt

      - name: Build
        run: |
          cd immortalwrt
          echo "src-git nikki https://github.com/nikkinikki-org/OpenWrt-nikki.git;main" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp ../.config ./
          make defconfig
          make download
          make V=s -j$(nproc)
          ls -l bin/targets/rockchip/armv8/
          cat bin/targets/rockchip/armv8/immortalwrt-rockchip-armv8-friendlyarm_nanopi-r5c.manifest
      - uses: actions/upload-artifact@v4
        with:
          name: images
          path: /home/runner/work/cicd/cicd/immortalwrt/bin/targets/rockchip/armv8/*.gz
          compression-level: 0
