# This is a basic workflow to help you get started with Actions

name: Openwrt

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Clone repository
        run: git clone -b master --single-branch --filter=blob:none https://github.com/immortalwrt/immortalwrt

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'

      - name: Build
        run: |
          cat /proc/cpuinfo
          cp .config ./immortalwrt/
          cd immortalwrt
          ls -a
          echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main" >> feeds.conf.default
          echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main" >> feeds.conf.default
          cat feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make download V=s
          # make V=s